//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appEscritorio.Miservicio {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Miservicio.ServicioRegistrarPublicacionesSoap")]
    public interface ServicioRegistrarPublicacionesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPublicaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarPublicaciones(appEscritorio.Miservicio.Publicaciones objpubli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPublicaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarPublicacionesAsync(appEscritorio.Miservicio.Publicaciones objpubli);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Publicaciones : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPublicacionField;
        
        private string nombreField;
        
        private double precioField;
        
        private string descripcionField;
        
        private string telefonoField;
        
        private string estratoField;
        
        private string direccionField;
        
        private int numeroHabitacionesField;
        
        private int idUsuarioField;
        
        private int idTipoField;
        
        private int idEstadoField;
        
        private int idCiudadField;
        
        private int idCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPublicacion {
            get {
                return this.idPublicacionField;
            }
            set {
                this.idPublicacionField = value;
                this.RaisePropertyChanged("IdPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("Precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Estrato {
            get {
                return this.estratoField;
            }
            set {
                this.estratoField = value;
                this.RaisePropertyChanged("Estrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int NumeroHabitaciones {
            get {
                return this.numeroHabitacionesField;
            }
            set {
                this.numeroHabitacionesField = value;
                this.RaisePropertyChanged("NumeroHabitaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("IdTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int IdCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                this.idCiudadField = value;
                this.RaisePropertyChanged("IdCiudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int IdCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("IdCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioRegistrarPublicacionesSoapChannel : appEscritorio.Miservicio.ServicioRegistrarPublicacionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistrarPublicacionesSoapClient : System.ServiceModel.ClientBase<appEscritorio.Miservicio.ServicioRegistrarPublicacionesSoap>, appEscritorio.Miservicio.ServicioRegistrarPublicacionesSoap {
        
        public ServicioRegistrarPublicacionesSoapClient() {
        }
        
        public ServicioRegistrarPublicacionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistrarPublicacionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarPublicacionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarPublicacionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet mtdListarProductos() {
            return base.Channel.mtdListarProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarProductosAsync() {
            return base.Channel.mtdListarProductosAsync();
        }
        
        public int mtdRegistrarPublicaciones(appEscritorio.Miservicio.Publicaciones objpubli) {
            return base.Channel.mtdRegistrarPublicaciones(objpubli);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarPublicacionesAsync(appEscritorio.Miservicio.Publicaciones objpubli) {
            return base.Channel.mtdRegistrarPublicacionesAsync(objpubli);
        }
    }
}
